version: "3"
services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - envMain_docker.env
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
    ports:
      - 5000:5000
      - 9229:9229
    depends_on:
      - postgres
    restart: always
    networks:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5433:5432"
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - docker.env
    networks:
      - postgres

  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
